// <auto-generated />
using System;
using DateAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DateAccess.Migrations
{
    [DbContext(typeof(CarajeDbContext))]
    partial class CarajeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DateAccess.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DateAccess.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ColorCar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discription")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelCar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ColorCar = "Black",
                            Discription = "Розгінна динаміка (0-100 км / год), сек.	3,9\nМаксимальна швидкість, км / год	225\nПотужність двигуна, к.с.	544",
                            ImagePath = "BMW_i4_M50.jpg",
                            ModelCar = "BMW i4 M50",
                            Price = 2902760,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ColorCar = "Blue",
                            Discription = "Розгінна динаміка (0-100 км / год), сек.	3,9\nМаксимальна швидкість, км / год	225\nПотужність двигуна, к.с.	544",
                            ImagePath = "bmw-i4-m50-blue.jpg",
                            ModelCar = "BMW i4 M50",
                            Price = 2942351,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ColorCar = "Grey",
                            Discription = "Розгінна динаміка (0-100 км / год), сек.	3,9\nМаксимальна швидкість, км / год	225\nПотужність двигуна, к.с.	544",
                            ImagePath = "bmw-i4-m50-grey.jpg",
                            ModelCar = "BMW i4 M50",
                            Price = 2964435,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ColorCar = "Black",
                            Discription = "Розгінна динаміка (0-100 км / год), сек.	6,8\nМаксимальна швидкість, км / год	180\nПотужність двигуна, к.с.	210 (286)",
                            ImagePath = "bmw-ix3-m-sport-black.jpg",
                            ModelCar = "BMW iX3 M Sport",
                            Price = 2504303,
                            Quantity = 32
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ColorCar = "Red",
                            Discription = "Highlander отримав гібридну силову установку четвертого покоління, яка дозволяє вам насолоджуватися усіма перевагами великого кросовера без шкоди для його потужності та екологічності. Завдяки 2,5-літровому гібридному двигуну Hybrid Dynamic Force потужністю 248 к. с. Highlander пропонує провідний у своєму класі баланс потужності та ефективності.",
                            ImagePath = "gold-car.png",
                            ModelCar = "Toyota Highlander Hybrid",
                            Price = 888282,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            ColorCar = "Gold",
                            Discription = "Завдяки переконливому кліренсу та високій посадці за кермом компактний Yaris Cross надає упевненості при русі містом. Насолоджуйтеся подорожжю із сучасними функціями комфорту та містким салоном, що відповідає повсякденним потребам.",
                            ImagePath = "gold-car.png",
                            ModelCar = "Yaris Cross",
                            Price = 1058322,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ColorCar = "Grey",
                            Discription = "У 2006 році назві Corolla виповнилося 40 років, протягом яких змінилося десять поколінь цих доступних і надійних автомобілів, а загальний обсяг випуску перевалив за 32 мільйонів. І ця рекордна цифра продажів, занесена до Книги рекордів Гіннесса, збільшується щорічно.",
                            ImagePath = "white-car.png",
                            ModelCar = "Corola",
                            Price = 757620,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            ColorCar = "Red",
                            Discription = "Нові Citroën C4 та ë-C4 з високим дорожнім просвітом, великими колесами та зручними розмірами виглядають готовими до будь-яких випробувань. Вони не тільки місткі, але й аеродинамічні.",
                            ImagePath = "Qwiqlu-car.jpg",
                            ModelCar = "C4 & Ë-C4",
                            Price = 1018300,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            ColorCar = "Grey",
                            Discription = "Новий плагін-гібрид Citroën C5 Aircross, що підходить для будь-яких щоденних поїздок, пропонує плавний і динамічний рух із потужністю 180 к.с. із двигуном внутрішнього згоряння й електродвигуном на 81,2 кВт (110 к.с.) із загальною потужністю 225 к.с. й обертальним моментом 360 Н-м.",
                            ImagePath = "Citroen-C5-Aircross.jpg",
                            ModelCar = "CITROEN C5 AIRCROSS",
                            Price = 1018300,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            ColorCar = "Orange",
                            Discription = "Надійний та перевірений часом і досвідом повний привод залишається головною перевагою оновленого Renault Duster. Завдяки зручним режимам роботи 2WD, AUTO або 4WD LOCK кожен водій може приборкати бездоріжжя. Повноприводний новий Renault Duster 4x4 можна купити як з бензиновим атмосферним, так і з дизельним турбо двигуном.",
                            ImagePath = "Orange.jpg",
                            ModelCar = "DUSTER",
                            Price = 1018300,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            ColorCar = "Blue",
                            Discription = "Новий Renault EXPRESS поєднав у собі фірмові характеристики Renault, які підкреслять ваш смак та педантичність вибору. Ви пишатиметесь своїм Express: виразна передня частина із широким капотом, хромована радіаторна решітка, фірмові денні світлодіодні ліхтарі тощо. Саме цей достойний силует без зайвих деталей надійно супроводжуватиме вас у щоденних справах!",
                            ImagePath = "Blue-Silver.jpg",
                            ModelCar = "RENAULT EXPRESS",
                            Price = 1100300,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            ColorCar = "Blue",
                            Discription = "Вражаюча форма нового PEUGEOT 408 характеризується динамічною натхненною позицією фастбеку. Сучасна елегантність фастбеку виділяє його на дорозі. Завдяки підвищеному дорожньому просвіту, але водночас помірній висоті, його спортивний дизайн і плавні лінії підкреслюють його аеродинамічні властивості. ",
                            ImagePath = "CarCar.jpg",
                            ModelCar = "PEUGEOT 408",
                            Price = 1000000,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            ColorCar = "White",
                            Discription = "Вражаюча форма нового PEUGEOT 408 характеризується динамічною натхненною позицією фастбеку. Сучасна елегантність фастбеку виділяє його на дорозі. Завдяки підвищеному дорожньому просвіту, але водночас помірній висоті, його спортивний дизайн і плавні лінії підкреслюють його аеродинамічні властивості. Відкрийте для себе технологічний кросовер PEUGEOT 3008 з його інноваційним та натхненним дизайном, який підносить вишуканість на ще вищий рівень, більш елегантний та футуристичний. Його виразні лінії кузова поєднують силу, динаміку та плавність. Для підвищення рівня Вашого комфорту та безпеки було впроваджено низку новаторських технологій та розроблено: сучасний, вдосконалений та просторий салон PEUGEOT 3008 з концепцією організації простору водія PEUGEOT i-Cockpit.",
                            ImagePath = "Run.jpg",
                            ModelCar = "PEUGEOT 3008 ",
                            Price = 970000,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            ColorCar = "White",
                            Discription = "Відкрийте для себе PEUGEOT 2008 або електрокросовер PEUGEOT 2008: компактний, потужний, динамічний та економічний кросовер.\r\nНасолоджуйтесь динамікою під час руху за рахунок сучаних технологій, які забезпечують тишу та комфорт в салоні автомобіля.",
                            ImagePath = "OrangeCar.jpg",
                            ModelCar = "PEUGEOT 2008",
                            Price = 1370000,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("DateAccess.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Citroen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Peugeot"
                        });
                });

            modelBuilder.Entity("DateAccess.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdCar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DateAccess.Models.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Storage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5
                        },
                        new
                        {
                            Id = 6,
                            CarId = 6
                        },
                        new
                        {
                            Id = 7,
                            CarId = 7
                        },
                        new
                        {
                            Id = 8,
                            CarId = 8
                        },
                        new
                        {
                            Id = 9,
                            CarId = 9
                        },
                        new
                        {
                            Id = 10,
                            CarId = 10
                        },
                        new
                        {
                            Id = 11,
                            CarId = 11
                        },
                        new
                        {
                            Id = 12,
                            CarId = 12
                        },
                        new
                        {
                            Id = 13,
                            CarId = 13
                        },
                        new
                        {
                            Id = 14,
                            CarId = 14
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DateAccess.Models.Car", b =>
                {
                    b.HasOne("DateAccess.Models.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DateAccess.Models.Order", b =>
                {
                    b.HasOne("DateAccess.Models.AppUser", null)
                        .WithMany("Orders")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("DateAccess.Models.Storage", b =>
                {
                    b.HasOne("DateAccess.Models.Car", "Car")
                        .WithMany("Storage")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DateAccess.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DateAccess.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DateAccess.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DateAccess.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DateAccess.Models.AppUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DateAccess.Models.Car", b =>
                {
                    b.Navigation("Storage");
                });

            modelBuilder.Entity("DateAccess.Models.Category", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
